[package]
name = "safe-client-gateway"
version = "0.1.0"
authors = ["jpalvarezl <jose.alvarez@gnosis.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rocket_codegen = "0.4.5"

ethereum-types= { version = "0.8.0", features = ["serialize"]}

serde = { version = "1.0", features = ["derive"] }